
1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:                                                                                 
   Region A: [10, 15, 12, 8, 14]                                                                      
   Region B: [18, 20, 16, 22, 25]                                                                               
   Calculate the mean sales for each region.


In [1]:
import numpy as np
RegionA = [10, 15, 12, 8, 14]
RegionB = [18, 20, 16, 22, 25]
print(np.mean(RegionA))
print(np.mean(RegionB))

11.8
20.2


2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:                                                                                                        
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]                                                                     
   Calculate the mode of the survey responses.


In [2]:
import statistics
data = [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
print(statistics.mode(data))

4


3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]                                                                    
   Department B: [4500, 5500, 5800, 6000, 5200]                                                                
   Calculate the median salary for each department.                                                             

In [3]:
DepartmentA = [5000, 6000, 5500, 7000]
DepartmentB = [4500, 5500, 5800, 6000, 5200]
print(statistics.median(DepartmentA))
print(statistics.median(DepartmentB))

5750.0
5500


4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]                                                                            
   Calculate the range of the stock prices.                                                                    

In [4]:
data=[25.5, 24.8, 26.1, 25.3, 24.9]
print(statistics.variance(data))

0.2720000000000007


5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:                                                                        
   Group A: [85, 90, 92, 88, 91]                                                                                  
   Group B: [82, 88, 90, 86, 87]                                                                                        
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.

In [5]:
import math
def squaresum(list):
    sm=0
    for i in list:
        sm += i*i
    return sm
def sumsquare(list):
    sm=0
    for i in list:
        sm+=i
    return sm*sm
GroupA = [85, 90, 92, 88, 91]
GroupB = [82, 88, 90, 86, 87]
m1 = np.mean(GroupA)
m2 = np.mean(GroupB)
Na= len(GroupA)
Nb = len(GroupB)
df = (Na-1)+(Nb-1)
A2 = sumsquare(GroupA)
B2 = sumsquare(GroupB)
S2A = squaresum(GroupA)
S2B = squaresum(GroupB)
T = (m1-m2)/math.sqrt((1/Na+1/Nb)*((A2-S2A/Na)+(B2-S2B/Nb))*(1/df))
T

0.01909145761992171

6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]                                                   
   Sales (in thousands): [25, 30, 28, 20, 26]                                                               
   Calculate the correlation coefficient between advertising expenditure and sales.                            

In [14]:
Expenditure = [10, 15, 12, 8, 14]
Sales = [25, 30, 28, 20, 26]
print(np.corrcoef(Expenditure,Sales))

[[1.         0.87575114]
 [0.87575114 1.        ]]


7. Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:   
   [160, 170, 165, 155, 175, 180, 170]                                                                     
   Calculate the standard deviation of the heights.                                                       

In [11]:
data = [160, 170, 165, 155, 175, 180, 170]
statistics.stdev(data)

8.591246929842246

8. Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:                  
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]                                                                                              
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]                                                                              
   Perform a linear regression analysis to predict job satisfaction based on employee tenure.                                               


In [45]:
import pandas as pd
X1 = [2, 3, 5, 4, 6, 2, 4]
y1= [7, 8, 6, 9, 5, 7, 6]
df = pd.DataFrame()
df['x1'] = X1
df['y1'] = y1
X = df.drop('y1',axis =1)
y = df['y1']

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [47]:
X_train.shape,X_test.shape

((4, 1), (3, 1))

In [48]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [49]:
X_train_scaled

array([[ 0.30151134],
       [ 1.50755672],
       [-0.90453403],
       [-0.90453403]])

In [52]:
## Linerar Regression Model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
linreg=LinearRegression()
linreg.fit(X_train_scaled,y_train)
y_pred=linreg.predict(X_test_scaled)
mae=mean_absolute_error(y_test,y_pred)
score=r2_score(y_test,y_pred)
print("Mean absolute error", mae)
print("R2 Score", score)

Mean absolute error 2.242424242424242
R2 Score -26.79338842975206


9. Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:                                                              
   Medication A: [10, 12, 14, 11, 13]                                                                       
   Medication B: [15, 17, 16, 14, 18]                                                                      
   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean  recovery times between the two medications.


In [53]:
from scipy.stats import f_oneway
MedicationA = [10, 12, 14, 11, 13]
MedicationB = [15, 17, 16, 14, 18]
f_oneway(MedicationA,MedicationB)

F_onewayResult(statistic=16.0, pvalue=0.003949772803445326)

10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is
 as follows:                                                                                                 
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]                                                                         
    Calculate the 75th percentile of the feedback ratings.


In [54]:
import numpy as np
list = [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
np.percentile(list,75)

8.75

11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:                                                                         
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]                                                                     
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [2]:
import pandas as pd
import scipy.stats as stats
df = pd.DataFrame()
df['weight'] = [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
t_statistic, p_value = stats.ttest_1samp(a=df, popmean=10)
print(t_statistic , p_value)

[1.51265845] [0.19077595]


12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:                                                                            
    Design A: [100, 120, 110, 90, 95]                                                                               
    Design B: [80, 85, 90, 95, 100]                                                                              
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


In [5]:
from scipy.stats import chi2_contingency
data = [[100, 120, 110, 90, 95],[80, 85, 90, 95, 100]]
stat,p,dof,expected = chi2_contingency(data)
print('stats',stat)
print('P value',p)
print('expected ',expected)

stats 6.110658166925435
P value 0.19103526314060293
expected  [[ 96.06217617 109.40414508 106.7357513   98.73056995 104.06735751]
 [ 83.93782383  95.59585492  93.2642487   86.26943005  90.93264249]]


13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:                                                                                          
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]                                                                               
    Calculate the 95% confidence interval for the population mean satisfaction score.                       

In [10]:
import numpy as np
import math
import statistics as stat
lst = [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
df = len(lst)-1
t_value = 2.262
s = stat.stdev(lst)
se = s/math.sqrt(len(lst))
av = np.mean(lst)
upper = av + (se*t_value)
lower = av - (se*t_value)
print('upper limit',upper)
print('lower limit',lower)

upper limit 8.756379378546681
lower limit 7.043620621453319


14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:                                                                                                      
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]                                                     
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]                                                         
    Perform a simple linear regression to predict performance based on temperature.


In [11]:
import pandas as pd
X1 = [20, 22, 23, 19, 21]
y1= [8, 7, 9, 6, 8]
df = pd.DataFrame()
df['x1'] = X1
df['y1'] = y1
X = df.drop('y1',axis =1)
y = df['y1']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
X_train_scaled

array([[ 1.37281295],
       [-0.39223227],
       [-0.98058068]])

In [15]:
## Linerar Regression Model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
linreg=LinearRegression()
linreg.fit(X_train_scaled,y_train)
y_pred=linreg.predict(X_test_scaled)
mae=mean_absolute_error(y_test,y_pred)
score=r2_score(y_test,y_pred)
print("Mean absolute error", mae)
print("R2 Score", score)

Mean absolute error 0.8269230769230766
R2 Score -3.7603550295857984


15. Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:                                 
    Group A: [4, 3, 5, 2, 4]                                                                                     
 Group B: [3, 2, 4, 3, 3]                                                                                    
    Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.


In [17]:
from scipy.stats import mannwhitneyu
Group1 = [4, 3, 5, 2, 4]
Group2 = [3, 2, 4, 3, 3]
stat,p_value = mannwhitneyu(Group1,Group2)
print('Stats',stat)
print('P_value',p_value)

Stats 17.0
P_value 0.380836480306712


16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:       
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]                                                                      
    Calculate the interquartile range (IQR) of the ages.


In [18]:
import numpy as np
lst = [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
Q1= np.percentile(lst,25)
Q3 = np.percentile(lst,75)
IQR = Q3-Q1
print('Interquartile Range',IQR)

Interquartile Range 22.5


17. Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:                                                                 
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]                                                                    
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]                                                                    
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]                                                                     
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.


In [19]:
from scipy import stats
AlgorithmA = [0.85, 0.80, 0.82, 0.87, 0.83]
AlgorithmB = [0.78, 0.82, 0.84, 0.80, 0.79]
AlgorithmC = [0.90, 0.88, 0.89, 0.86, 0.87]
result = stats.kruskal(AlgorithmA,AlgorithmB,AlgorithmC)
result

KruskalResult(statistic=9.696947935368053, pvalue=0.007840333026249539)

18. Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:          
    Price (in dollars): [10, 15, 12, 8, 14]                                                                      
    Sales: [100, 80, 90, 110, 95]                                                                                
    Perform a simple linear regression to predict
 sales based on price.


In [20]:
import pandas as pd
X1 =  [10, 15, 12, 8, 14]
y1=  [100, 80, 90, 110, 95]
df = pd.DataFrame()
df['x1'] = X1
df['y1'] = y1
X = df.drop('y1',axis =1)
y = df['y1']

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
X_train_scaled

array([[ 1.22474487],
       [ 0.        ],
       [-1.22474487]])

In [24]:
## Linerar Regression Model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
linreg=LinearRegression()
linreg.fit(X_train_scaled,y_train)
y_pred=linreg.predict(X_test_scaled)
mae=mean_absolute_error(y_test,y_pred)
score=r2_score(y_test,y_pred)
print("Mean absolute error", mae)
print("R2 Score", score)

Mean absolute error 10.0
R2 Score -1.2222222222222223


19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:                                                                                      
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]                                                                               
    Calculate the standard error of the mean satisfaction score.


In [27]:
from scipy.stats import sem
data = [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
result = sem(data)
result

0.30550504633038933

20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:                                                                                       
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]                                                    
    Sales (in thousands): [25, 30, 28, 20, 26]                                                                    
    Perform a multiple regression analysis to predict sales based on advertising expenditure.            


In [28]:
import pandas as pd
X1 =  [10, 15, 12, 8, 14]
y1=   [25, 30, 28, 20, 26]
df = pd.DataFrame()
df['x1'] = X1
df['y1'] = y1
X = df.drop('y1',axis =1)
y = df['y1']

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
X_train_scaled

array([[ 1.22474487],
       [ 0.        ],
       [-1.22474487]])

In [32]:
## Linerar Regression Model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
linreg=LinearRegression()
linreg.fit(X_train_scaled,y_train)
y_pred=linreg.predict(X_test_scaled)
mae=mean_absolute_error(y_test,y_pred)
score=r2_score(y_test,y_pred)
print("Mean absolute error", mae)
print("R2 Score", score)

Mean absolute error 5.333333333333329
R2 Score -6.361111111111098
